##===- projects/sample/tools/sample/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=..
LIBRARYNAME = libHeapToss
LOADABLE_MODULE = 1
USEDLIBS =

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

